x-common-settings: &common-settings
  image: agarwalsaurav/pac:noble
  privileged: true
  network_mode: host
  ipc: host
  pid: host
  environment:
    - RCUTILS_COLORIZED_OUTPUT=1
    - PAC_WS=/workspace
  working_dir: /workspace
  volumes:
    - ${PAC_WS}:/workspace:rw

x-ros-launch-file: &ros-launch-file
  command: >
    bash -c -i "ros2 launch /workspace/launch/starling_offboard.yaml"

services:
  px4_1:
    <<: [*common-settings, *ros-launch-file]
    container_name: px4_1
    environment:
      - ROS_NAMESPACE=px4_1
      - ROBOT_ID=1

  px4_2:
    <<: [*common-settings, *ros-launch-file]
    container_name: px4_2
    environment:
      - ROS_NAMESPACE=px4_2
      - ROBOT_ID=2

  px4_3:
    <<: [*common-settings, *ros-launch-file]
    container_name: px4_3
    environment:
      - ROS_NAMESPACE=px4_3
      - ROBOT_ID=3

  px4_4:
    <<: [*common-settings, *ros-launch-file]
    container_name: px4_4
    environment:
      - ROS_NAMESPACE=px4_4
      - ROBOT_ID=4

  px4_5:
    <<: [*common-settings, *ros-launch-file]
    container_name: px4_5
    environment:
      - ROS_NAMESPACE=px4_5
      - ROBOT_ID=5

  px4_6:
    <<: [*common-settings, *ros-launch-file]
    container_name: px4_6
    environment:
      - ROS_NAMESPACE=px4_6
      - ROBOT_ID=6

  px4_7:
    <<: [*common-settings, *ros-launch-file]
    container_name: px4_7
    environment:
      - ROS_NAMESPACE=px4_7
      - ROBOT_ID=7

  px4_8:
    <<: [*common-settings, *ros-launch-file]
    container_name: px4_8
    environment:
      - ROS_NAMESPACE=px4_8
      - ROBOT_ID=8

